=== ardall-leo/creditinfo_task/data.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Batch" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="Batch" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Contract">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ContractCode" type="xs:string" minOccurs="0" />
              <xs:element name="ContractData" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="PhaseOfContract" type="xs:string" minOccurs="0" />
                    <xs:element name="DateOfLastPayment" type="xs:string" minOccurs="0" />
                    <xs:element name="NextPaymentDate" type="xs:string" minOccurs="0" />
                    <xs:element name="DateAccountOpened" type="xs:string" minOccurs="0" />
                    <xs:element name="RealEndDate" type="xs:string" minOccurs="0" />
                    <xs:element name="OriginalAmount" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Value" type="xs:string" minOccurs="0" />
                          <xs:element name="Currency" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="InstallmentAmount" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Value" type="xs:string" minOccurs="0" />
                          <xs:element name="Currency" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="CurrentBalance" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Value" type="xs:string" minOccurs="0" />
                          <xs:element name="Currency" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="OverdueBalance" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Value" type="xs:string" minOccurs="0" />
                          <xs:element name="Currency" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Individual" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="CustomerCode" type="xs:string" minOccurs="0" />
                    <xs:element name="FirstName" type="xs:string" minOccurs="0" />
                    <xs:element name="LastName" type="xs:string" minOccurs="0" />
                    <xs:element name="Gender" type="xs:string" minOccurs="0" />
                    <xs:element name="DateOfBirth" type="xs:string" minOccurs="0" />
                    <xs:element name="IdentificationNumbers" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="SubjectRole" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="CustomerCode" type="xs:string" minOccurs="0" />
                    <xs:element name="RoleOfCustomer" type="xs:string" minOccurs="0" />
                    <xs:element name="GuaranteeAmount" type="xs:string" minOccurs="0" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ardall-leo/creditinfo_task/data.xml
<?xml version="1.0"?>
<Batch xmlns="http://creditinfo.com/schemas/Sample/Data" xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:schemaLocation="https://creditinfocandidate2k.z16.web.core.windows.net/assets/Data.xsd">
	<Contract>
		<ContractCode>1</ContractCode>
		<ContractData>
			<PhaseOfContract>Open</PhaseOfContract>
			<OriginalAmount>
				<Value>2</Value>
				<Currency></Currency>
			</OriginalAmount>
			<InstallmentAmount>
				<Value>2</Value>
				<Currency></Currency>
			</InstallmentAmount>
			<CurrentBalance>
				<Value>3</Value>
				<Currency></Currency>
			</CurrentBalance>
			<OverdueBalance>
				<Value>4</Value>
				<Currency></Currency>
			</OverdueBalance>
			<DateOfLastPayment>2022-12-20Z</DateOfLastPayment>
			<NextPaymentDate>2022-12-20Z</NextPaymentDate>
			<DateAccountOpened>2022-12-20Z</DateAccountOpened>
			<RealEndDate>2022-12-20Z</RealEndDate>
		</ContractData>
		<Individual>
			<CustomerCode></CustomerCode>
			<FirstName></FirstName>
			<LastName></LastName>
			<Gender></Gender>
			<DateOfBirth>2022-12-20Z</DateOfBirth>
			<IdentificationNumbers></IdentificationNumbers>
		</Individual>
		<SubjectRole>
			<CustomerCode></CustomerCode>
			<RoleOfCustomer></RoleOfCustomer>
			<GuaranteeAmount>3</GuaranteeAmount>
		</SubjectRole>
	</Contract>
	<Contract>
		<ContractCode>1</ContractCode>
		<ContractData>
			<PhaseOfContract>Open</PhaseOfContract>
			<OriginalAmount>
				<Value>2p</Value>
				<Currency></Currency>
			</OriginalAmount>
			<InstallmentAmount>
				<Value>2</Value>
				<Currency></Currency>
			</InstallmentAmount>
			<CurrentBalance>
				<Value>3</Value>
				<Currency></Currency>
			</CurrentBalance>
			<OverdueBalance>
				<Value>4</Value>
				<Currency></Currency>
			</OverdueBalance>
			<DateOfLastPayment>2022-12-20Z</DateOfLastPayment>
			<NextPaymentDate>2022-12-20Z</NextPaymentDate>
			<DateAccountOpened>2022-12-20Z</DateAccountOpened>
			<RealEndDate>2022-12-20Z</RealEndDate>
		</ContractData>
		<Individual>
			<CustomerCode></CustomerCode>
			<FirstName></FirstName>
			<LastName></LastName>
			<Gender></Gender>
			<DateOfBirth>2022-12-20Z</DateOfBirth>
			<IdentificationNumbers></IdentificationNumbers>
		</Individual>
		<SubjectRole>
			<CustomerCode></CustomerCode>
			<RoleOfCustomer></RoleOfCustomer>
			<GuaranteeAmount>3</GuaranteeAmount>
		</SubjectRole>
	</Contract>
</Batch>

=== ardall-leo/creditinfo_task/sample.xml
<?xml version="1.0" encoding="utf-8"?>
<Batch xmlns="http://creditinfo.com/schemas/Sample/Data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="https://creditinfocandidate2k.z16.web.core.windows.net/assets/Data.xsd">
  <Contract>
    <ContractCode>1str1234</ContractCode>
    <ContractData>
      <PhaseOfContract>Open</PhaseOfContract>
      <OriginalAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </OriginalAmount>
      <InstallmentAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </InstallmentAmount>
      <CurrentBalance>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </CurrentBalance>
      <OverdueBalance>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </OverdueBalance>
      <DateOfLastPayment>2012-12-13</DateOfLastPayment>
      <NextPaymentDate>2012-12-13</NextPaymentDate>
      <DateAccountOpened>2012-12-13</DateAccountOpened>
      <RealEndDate>2012-12-13</RealEndDate>
    </ContractData>
    <Individual>
      <CustomerCode>str1234</CustomerCode>
      <FirstName>str1234</FirstName>
      <LastName>str1234</LastName>
      <Gender>Male</Gender>
      <DateOfBirth>2012-12-13</DateOfBirth>
      <IdentificationNumbers>
        <NationalID>ID1234567</NationalID>
      </IdentificationNumbers>
    </Individual>
    <SubjectRole>
      <CustomerCode>str1234</CustomerCode>
      <RoleOfCustomer>MainDebtor</RoleOfCustomer>
      <GuaranteeAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </GuaranteeAmount>
    </SubjectRole>
    <SubjectRole>
      <CustomerCode>str1234</CustomerCode>
      <RoleOfCustomer>MainDebtor</RoleOfCustomer>
      <GuaranteeAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </GuaranteeAmount>
    </SubjectRole>
  </Contract>
  <Contract>
    <ContractCode>ContractCode2</ContractCode>
    <ContractData>
      <PhaseOfContract>Closed</PhaseOfContract>
      <OriginalAmount>
        <Value>-79228162514264337593543950335</Value>
        <Currency>AFN</Currency>
      </OriginalAmount>
      <InstallmentAmount>
        <Value>-79228162514264337593543950335</Value>
        <Currency>AFN</Currency>
      </InstallmentAmount>
      <CurrentBalance>
        <Value>-79228162514264337593543950335</Value>
        <Currency>AFN</Currency>
      </CurrentBalance>
      <OverdueBalance>
        <Value>-79228162514264337593543950335</Value>
        <Currency>AFN</Currency>
      </OverdueBalance>
      <DateOfLastPayment>0001-01-01</DateOfLastPayment>
      <NextPaymentDate>0001-01-01</NextPaymentDate>
      <DateAccountOpened>0001-01-01</DateAccountOpened>
      <RealEndDate>0001-01-01</RealEndDate>
    </ContractData>
    <Individual>
      <CustomerCode>CustomerCode4</CustomerCode>
      <FirstName>FirstName4</FirstName>
      <LastName>LastName4</LastName>
      <Gender>Female</Gender>
      <DateOfBirth>1899-11-30</DateOfBirth>
      <IdentificationNumbers>
        <NationalID>NationalID4</NationalID>
      </IdentificationNumbers>
    </Individual>
    <Individual>
      <CustomerCode>CustomerCode5</CustomerCode>
      <FirstName>FirstName5</FirstName>
      <LastName>LastName5</LastName>
      <Gender></Gender>
      <DateOfBirth>1900-02-02</DateOfBirth>
      <IdentificationNumbers>
        <NationalID>NationalID5</NationalID>
      </IdentificationNumbers>
    </Individual>
    <Individual>
      <CustomerCode>CustomerCode6</CustomerCode>
      <FirstName>FirstName6</FirstName>
      <LastName>LastName6</LastName>
      <Gender>NotSpecified</Gender>
      <DateOfBirth>0001-02-02</DateOfBirth>
      <IdentificationNumbers>
        <NationalID>NationalID6</NationalID>
      </IdentificationNumbers>
    </Individual>
    <SubjectRole>
      <CustomerCode>CustomerCode4</CustomerCode>
      <RoleOfCustomer>MainDebtor</RoleOfCustomer>
      <GuaranteeAmount>
        <Value>0.9</Value>
        <Currency>AMD</Currency>
      </GuaranteeAmount>
    </SubjectRole>
    <SubjectRole>
      <CustomerCode>CustomerCode5</CustomerCode>
      <RoleOfCustomer>CoDebtor</RoleOfCustomer>
      <GuaranteeAmount>
        <Value>1.1</Value>
        <Currency>ANG</Currency>
      </GuaranteeAmount>
    </SubjectRole>
    <SubjectRole>
      <CustomerCode>CustomerCode6</CustomerCode>
      <RoleOfCustomer>Guarantor</RoleOfCustomer>
      <GuaranteeAmount>
        <Value>-79228162514264337593543950335</Value>
        <Currency>AOA</Currency>
      </GuaranteeAmount>
    </SubjectRole>
  </Contract>
  <Contract>
    <ContractCode>ase</ContractCode>
    <ContractData>
      <PhaseOfContract>Open</PhaseOfContract>
      <OriginalAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </OriginalAmount>
      <InstallmentAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </InstallmentAmount>
      <CurrentBalance>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </CurrentBalance>
      <OverdueBalance>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </OverdueBalance>
      <DateOfLastPayment>2012-12-13</DateOfLastPayment>
      <NextPaymentDate>2012-12-13</NextPaymentDate>
      <DateAccountOpened>2012-12-13</DateAccountOpened>
      <RealEndDate>2012-12-13</RealEndDate>
    </ContractData>
    <Individual>
      <CustomerCode>str1234</CustomerCode>
      <FirstName>str1234</FirstName>
      <LastName>str1234</LastName>
      <Gender>Male</Gender>
      <DateOfBirth>2012-12-13</DateOfBirth>
      <IdentificationNumbers>
        <NationalID>ID1234567</NationalID>
      </IdentificationNumbers>
    </Individual>
    <SubjectRole>
      <CustomerCode>str1234</CustomerCode>
      <RoleOfCustomer>MainDebtor</RoleOfCustomer>
      <GuaranteeAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </GuaranteeAmount>
    </SubjectRole>
  </Contract>
  <Contract>
    <ContractCode>wew</ContractCode>
    <ContractData>
      <PhaseOfContract>Open</PhaseOfContract>
      <OriginalAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </OriginalAmount>
      <InstallmentAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </InstallmentAmount>
      <CurrentBalance>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </CurrentBalance>
      <OverdueBalance>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </OverdueBalance>
      <DateOfLastPayment>2012-12-13</DateOfLastPayment>
      <NextPaymentDate>2012-12-13</NextPaymentDate>
      <DateAccountOpened>2012-12-13</DateAccountOpened>
      <RealEndDate>2012-12-13</RealEndDate>
    </ContractData>
    <Individual>
      <CustomerCode>str1234</CustomerCode>
      <FirstName>str1234</FirstName>
      <LastName>str1234</LastName>
      <Gender>Male</Gender>
      <DateOfBirth>2012-12-13</DateOfBirth>
      <IdentificationNumbers>
        <NationalID>ID1234567</NationalID>
      </IdentificationNumbers>
    </Individual>
    <SubjectRole>
      <CustomerCode>str1234</CustomerCode>
      <RoleOfCustomer>MainDebtor</RoleOfCustomer>
      <GuaranteeAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </GuaranteeAmount>
    </SubjectRole>
  </Contract>
  <Contract>
    <ContractCode>AQ</ContractCode>
    <ContractData>
      <PhaseOfContract>Open</PhaseOfContract>
      <OriginalAmount>
        <Value>123.45</Value>
        <Currency>AEDX</Currency>
      </OriginalAmount>
      <InstallmentAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </InstallmentAmount>
      <CurrentBalance>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </CurrentBalance>
      <OverdueBalance>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </OverdueBalance>
      <DateOfLastPayment>2012-12-13</DateOfLastPayment>
      <NextPaymentDate>2012-12-13</NextPaymentDate>
      <DateAccountOpened>2012-12-13</DateAccountOpened>
      <RealEndDate>2012-12-13</RealEndDate>
    </ContractData>
    <Individual>
      <CustomerCode>str1234</CustomerCode>
      <FirstName>str1234</FirstName>
      <LastName>str1234</LastName>
      <Gender>Male</Gender>
      <DateOfBirth>2012-12-13</DateOfBirth>
      <IdentificationNumbers>
        <NationalID>ID1234567</NationalID>
      </IdentificationNumbers>
    </Individual>
    <SubjectRole>
      <CustomerCode>str1234</CustomerCode>
      <RoleOfCustomer>MainDebtor</RoleOfCustomer>
      <GuaranteeAmount>
        <Value>123.45</Value>
        <Currency>AED</Currency>
      </GuaranteeAmount>
    </SubjectRole>
  </Contract>
</Batch>
